name: 'prepare-helm-releases'
description: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  github_token:
    description: ''
    required: true
  checksum:
    description: ''
    default: ''
    required: false
  org_domain:
    description: ''
    default: ''
    required: false